language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gulp-cli
  - npm install -g codecov
script:
  - gulp build
  - gulp test
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov
